apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-servicebus
spec:
  type: pubsub.azure.servicebus
  metadata:
  - name: connectionString
    value: Endpoint=sb://gebasb.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=GjNNlnlZw/dcwlSOVEcJCX4kfzJWOBHnYoHKPUG0ma4=