apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: azureservicebus
  namespace: default
spec:
  vault:
    name: gebakv
    object:
      name: ServiceBus
      type: secret
  output:
    secret: 
      name: dapr-sb
      dataKey: ServiceBus
      type: opaque

    