apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: signalr
spec:
  type: bindings.azure.signalr
  metadata:
  - name: connectionString
    value: Endpoint
  - name: hub  # Optional
    value: influx