apiVersion: apps/v1
kind: Deployment
metadata:
  name: daprfunc
  namespace: default
  labels:
    app: daprfunc
spec:
  selector:
    matchLabels:
      app: daprfunc
  replicas: 1
  template:
    metadata:
      labels:
        app: daprfunc
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "dapr"
    spec:
      containers:
      - name: daprfunc
        image: docker.io/gbaeke/daprfunc:0.0.3
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: ProcessMessages
        - name: FUNCTIONS_WORKER_RUNTIME
          value: node
        - name: GEBAHUB
          valueFrom:
            secretKeyRef:
              name: dapr-event
              key: EventEndpoint
        - name: AzureWebJobsStorage
          valueFrom:
            secretKeyRef:
              name: dapr-storage
              key: AzureWebJobsStorage
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: daprfunc-keda
  namespace: default
  labels:
    deploymentName: daprfunc
spec:
  scaleTargetRef:
    deploymentName: daprfunc
  maxReplicaCount: 10
  triggers:
  - type: azure-eventhub
    metadata:
      type: eventHubTrigger
      name: IoTHubMessages
      direction: in
      eventHubName: gebahub-b
      connection: GEBAHUB
      cardinality: many
      consumerGroup: keda

